name: Python Script

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r logistics/gs_transportation/requirements.txt
          


      - name: Python Script
        env:
          secret_key: ${{secrets.TOKEN1}}
        run: python logistics/gs_transportation/gs_transportation.py




        