name: Python Script

on:
  schedule:
    - cron: '59 4 * * 1-6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r logistics/intercity/requirements.txt

      - name: Run Python Script
        env:
          secret_key: ${{ secrets.TOKEN1 }}
        run: python logistics/intercity/intercity.py

      - name: Run Gmail function
        run: python logistics/intercity/gmail_functions.py
