name: Python Script

on:
  schedule:
    - cron: '1 2-9/4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dealer/gsheet/requirements.txt

      - name: Run script
        run: python dealer/gsheet/monthly_updated_sheet.py
        # env:
        #   # Define any necessary environment variables here
        #   # VARIABLE_NAME: ${{ secrets.YOUR_SECRET }}  # Example for using secrets
