name: Python Script

on:
  schedule:
    - cron: '0 4 * * 1-6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dealer/monthly_updated_sheet_extra_data/requirements.txt

      - name: Run Python Script
        run: python "dealer/monthly_updated_sheet_extra_data/Monthly Updated sheet_extra_data.py"
