name: Python Script

on:
  schedule:
    - cron: '40 19,12 * * 1-6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dealer\report1\requirements.txt

      - name: Run script
        run: python "dealer/report1/reports1.py"
        env:
          secret_key: ${{ secrets.TOKEN1 }}
